### ISSUE TITLE
Add a search bar?

### ISSUE THREAD

**Issue by iotize** [FlexMonkey/Filterpedia#12]
You've added so many great filters that I sometimes struggle to find a specific one. (Take that as a compliment!)

Would you be interested in adding a search function to the filter list? I've been considering making a pull request, but wanted to check that you'd be interested in merging it, and that you're not already working on it.

**Comment by FlexMonkey** [comment]
Hi Ryan,

Thanks for the suggestion. I totally agree, since Filterpedia has grown into a monster repository of filters, a search bar is a much needed addition. I've also been thinking about adding favourites too (maybe saved to NSUserDefaults). 

If you find yourself with the time too add it, I'd gratefully accept your pull request :) I'm not working on it at the moment, so the code case is all yours!

Simon
