### ISSUE TITLE
More Permissive License, Perhaps?

### ISSUE THREAD

**Issue by perlmunger** [FlexMonkey/Filterpedia#23]
I don't want to presume that choosing GPL was not intentional, but are you aware that it does not allow for commercial use (distribution) unless the app you're using it in is also open-source (ref: http://softwareengineering.stackexchange.com/questions/47032/can-i-use-gpl-software-in-a-commercial-application)? Is there any chance you'd be willing to license it under something more permissive like MIT or BSD?

**Comment by FlexMonkey** [comment]
Hi, I'm in the process of moving it to Apache. Because of the contract I have with my current employer, I can't actually make any changes to this project until I get approval from them and I'm waiting on that approval right now. That will also allow me to move this to Swift 3 🙂

Hang tight - I'm hoping to get the all clear soon!

**Comment by perlmunger** [comment]
Cool! Apache is good too. Thanks. I'll keep an eye out.

**Comment by FlexMonkey** [comment]
That said, if you make a billion from one of my open-source filters, I expect a beer!

**Comment by perlmunger** [comment]
You got it! ;-)

**Comment by boourns** [comment]
@FlexMonkey hello, any update on license change?

Thanks
